influxDB:
  host: 127.0.0.1
  token: testtoken
  organization: my-org
  bucket: my-bucket
workload:
  logPerWorks: 100
  workerTemplates:
    - measurement: temperature
      tags:
        - test1=test1
        - test2=test2
      fields:
        - census
      workers: 1000
      emitInterval: 1000
    - measurement: luminance
      tags:
        - test3=test3
        - test4=test4
      fields:
        - lumen
      workers: 1000
      emitInterval: 2000